# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-09 07:42
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transformer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permissionmapper',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='permissionmapper',
            old_name='url_mapper_id',
            new_name='url_mapper',
        ),
        migrations.RenameField(
            model_name='urlaccesslogger',
            old_name='url_mapper_id',
            new_name='url_mapper',
        ),
        migrations.RenameField(
            model_name='urlmapper',
            old_name='allowed_headers',
            new_name='extra_headers',
        ),
        migrations.RemoveField(
            model_name='urlmapper',
            name='access_url',
        ),
        migrations.AddField(
            model_name='urlmapper',
            name='access_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='urlmapper',
            name='web_hook_url',
            field=models.URLField(unique=True),
        ),
    ]
