# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-11 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transformer', '0004_auto_20180110_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderMapper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_key', models.CharField(max_length=100)),
                ('header_value', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='urlmapper',
            name='extra_headers',
        ),
        migrations.AddField(
            model_name='headermapper',
            name='url_mapper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transformer.URLMapper'),
        ),
    ]
