# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-11 14:39
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import transformer.models


class Migration(migrations.Migration):

    dependencies = [
        ('transformer', '0005_auto_20180111_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLAccessLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_url', models.URLField()),
                ('web_hook_url', models.URLField()),
                ('access_method', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('input_data', django.contrib.postgres.fields.jsonb.JSONField(default=transformer.models.json_default)),
                ('output_data', django.contrib.postgres.fields.jsonb.JSONField(default=transformer.models.json_default)),
                ('response_data', models.TextField(default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='urlaccesslogger',
            name='url_mapper',
        ),
        migrations.DeleteModel(
            name='URLAccessLogger',
        ),
    ]
