# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-17 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformer', '0007_auto_20180112_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlaccesslog',
            name='output_data',
            field=models.TextField(default=''),
        ),
    ]
