# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-17 11:22
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import transformer.models


class Migration(migrations.Migration):

    dependencies = [
        ('transformer', '0008_auto_20180117_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlaccesslog',
            name='new_headers',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=transformer.models.json_default),
        ),
        migrations.AddField(
            model_name='urlaccesslog',
            name='old_headers',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=transformer.models.json_default),
        ),
    ]
